# Generated by Django 4.0.5 on 2022-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.IntegerField(max_length=5)),
                ('passwo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('phno', models.CharField(max_length=13)),
                ('pwd', models.CharField(max_length=20)),
                ('repwd', models.CharField(max_length=20)),
            ],
        ),
    ]
