# Generated by Django 4.0.5 on 2022-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0002_remove_hmodel_passwo_remove_hmodel_regnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmodel',
            name='slots',
            field=models.IntegerField(default=20, max_length=2),
        ),
    ]
