# Generated by Django 4.0.5 on 2022-09-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0003_hmodel_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmodel',
            old_name='email',
            new_name='username',
        ),
    ]
